### model
method: CC
feature_dim: 128
resnet: "ResNet34"
image_size: 224
instance_temperature: 0.5
cluster_temperature: 1.0

### device
device: cuda:0
num_workers: 8

### dataset
dataset_name: CIFAR10
data_dir: /data2/liangguanbao/opendeepclustering/datasets
cluster_num: 10

### output
output_dir: /data2/liangguanbao/opendeepclustering/saves/CC/CIFAR10

### train
epochs: 1000
batch_size: 256
lr: 0.0003
weight_decay: 0.
stopping_delta: 0.000001

### eval
eval_epochs: 1
eval_batch_size: 256