### model
dims:
  - 784
  - 500
  - 500
  - 2000
  - 10

### device
device: cuda:0
num_workers: 16

### dataset
dataset_name: mnist
data_dir: /data2/liangguanbao/opendeepclustering/datasets

### output
output_dir: /data2/liangguanbao/opendeepclustering/saves/mnist

### pretrain
pretrain_epochs: 300
finetune_epochs: 500
batch_size: 256

### train

### eval
eval_epochs: 1