### model
dims:
  - 784
  - 500
  - 500
  - 2000
  - 10
dropout_rate: 0.2

### device
device: cuda:0
num_workers: 16

### dataset
dataset_name: mnist
data_dir: /data2/liangguanbao/opendeepclustering/datasets

### output
output_dir: /data2/liangguanbao/opendeepclustering/saves/DEC/mnist

### pretrain
pretrain_epochs: 300
finetune_epochs: 500
batch_size: 256
lr: 0.1
momentum: 0.9
scheduler_step: 100
scheduler_gamma: 0.1

### train

### eval
eval_epochs: 1