low_dim: 128
tau: 1.0
tau2: 2.0
momentum: 0.5

### device
device: cuda:0
num_workers: 8

### dataset
dataset_name: CIFAR10
data_dir: /data2/liangguanbao/opendeepclustering/datasets
cluster_num: 10

### output
output_dir: /data2/liangguanbao/opendeepclustering/saves/IDFD/CIFAR10

### train
epochs: 2000
eval_epochs: 1
batch_size: 128
lr: 0.03
sgd_momentum: 0.9
weight_decay: 0.0005
milestones:
  - 600
  - 950
  - 1300
  - 1650
gamma: 0.1
stopping_delta: 0.000001